In [4]:
from sklearn import datasets, svm, metrics

# The digits dataset
digits = datasets.load_digits()

In [5]:
print(digits['DESCR'])

Optical Recognition of Handwritten Digits Data Set

Notes
-----
Data Set Characteristics:
    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is a

In [6]:
digits

{'DESCR': "Optical Recognition of Handwritten Digits Data Set\n===================================================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttp://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels ar

In [10]:
print(digits['images'][-2])

[[  0.   0.   2.  10.   7.   0.   0.   0.]
 [  0.   0.  14.  16.  16.  15.   1.   0.]
 [  0.   4.  16.   7.   3.  16.   7.   0.]
 [  0.   5.  16.  10.   7.  16.   4.   0.]
 [  0.   0.   5.  14.  14.  16.   4.   0.]
 [  0.   0.   0.   0.   0.  16.   2.   0.]
 [  0.   0.   4.   7.   7.  16.   2.   0.]
 [  0.   0.   5.  12.  16.  12.   0.   0.]]


In [11]:
print(digits['target'][0])

0


In [12]:
X = digits['images']
y = digits['target']
X.shape, y.shape

((1797, 8, 8), (1797,))

In [13]:
len(X)

1797

In [ ]:
from sklearn import cross_validation
rs = cross_validation.ShuffleSplit(len(X), n_iter=1,test_size=.25, random_state=0)
for train, test in rs:
    X_train = X[train]
    y_train = y[train]
    X_test = X[test]
    y_test = y[test]

In [ ]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activationtion
from keras.optimizers import SGD

model = Sequential()

model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='valid',
                        input_shape=(1, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adadelta')


In [1]:
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.utils import np_utils

batch_size = 128
nb_classes = 10
nb_epoch = 12

# input image dimensions
img_rows, img_cols = 28, 28
# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3

# the data, shuffled and split between tran and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

Using Theano backend.
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples


/home/faker/anaconda3/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")


In [2]:
# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

model = Sequential()

model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='valid',
                        input_shape=(1, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adadelta')

In [3]:
model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
          show_accuracy=True, verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, show_accuracy=True, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 1200s - loss: 0.2331 - acc: 0.9284 - val_loss: 0.0531 - val_acc: 0.9840
Epoch 2/12
60000/60000 [==============================] - 1170s - loss: 0.0879 - acc: 0.9739 - val_loss: 0.0420 - val_acc: 0.9860
Epoch 3/12
60000/60000 [==============================] - 1158s - loss: 0.0671 - acc: 0.9806 - val_loss: 0.0330 - val_acc: 0.9894
Epoch 4/12
60000/60000 [==============================] - 1162s - loss: 0.0538 - acc: 0.9842 - val_loss: 0.0310 - val_acc: 0.9895
Epoch 5/12
60000/60000 [==============================] - 1161s - loss: 0.0467 - acc: 0.9856 - val_loss: 0.0308 - val_acc: 0.9896
Epoch 6/12
60000/60000 [==============================] - 1158s - loss: 0.0412 - acc: 0.9873 - val_loss: 0.0323 - val_acc: 0.9893
Epoch 7/12
60000/60000 [==============================] - 1160s - loss: 0.0388 - acc: 0.9887 - val_loss: 0.0332 - val_acc: 0.9908
Epoch 8/12
60000/60000 [================